feat: define ast
XFreeCoder/x-filter pull request #4
Opened 2023-02-15 07:33 UTC by MrHeer

2023-02-15 07:40 UTC, thomaszdxsn requested changes

2023-02-15 07:40 UTC, thomaszdxsn commented on packages/core/src/ast.ts
> +export type TimestampCreatedTimeFilter = {
remove this

2023-02-15 07:40 UTC, thomaszdxsn commented on packages/core/src/ast.ts
> +export type TimestampLastEditedTimeFilter = {
remove this

2023-02-15 07:40 UTC, thomaszdxsn commented on packages/core/src/ast.ts
> +        | { or: Array<PropertyFilter> }
if interface like this, the max level is 2.

we should define more generic interface

2023-02-15 07:40 UTC, thomaszdxsn commented on packages/core/src/ast.ts
> +  | { is_empty: true }
camelCase, please

2023-02-16 05:52 UTC, ZZITE approved these changes

2023-03-05 19:44 UTC, thomaszdxsn approved these changes

2023-03-05 19:44 UTC, merged